### ISSUE TITLE
User Profile to show University (3)

### ISSUE THREAD

**Issue by uting98** [JiejayLan/unifreefrontend#60] opened 2019-11-16 02:35 UTC
Technical Background:
- User should be able to see their schools in a drop down menu on the navBar

Acceptance Criteria:
- Create a drop down menus for users to visualize their schools 
- See [Mouse Over Interaction](https://material-ui.com/components/popover/#mouse-over-interaction) for reference

**Comment by songrenzhao** [comment] 2019-11-30 17:42
Duplicate of #75

**Closed by songrenzhao** 2019-11-30 17:42 UTC
Labels: low priority
