### ISSUE TITLE
Create Comment Component (2)

### ISSUE THREAD

**Issue by uting98** [JiejayLan/unifreefrontend#57] opened 2019-11-16 02:24 UTC
Technical Technical
- User should be able to comment on `IndividualPost` page

Acceptance Criteria
- Create a component such that it will allow users to comment on the `IndividualPost` page, check [backend ticket](https://github.com/jinchen1036/rdb-crud-microservice/issues/78)

**Comment by nchen000** [comment] 2019-11-16 02:26
Is this a duplicate of issue #56 ?

**Comment by uting98** [comment] 2019-11-16 02:28
> Is this a duplicate of issue #56 ?

I think issue #56 is all the features we are going to implement in the following sprint, and we need to create sub issues based on the features song provided before grooming

**Closed** 2019-11-27 03:03 UTC
Labels: high priority
